const PicDatas = [
    {
        imgurl:'img/1.jpg',
        title:'Mountain',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/2.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'

    },
    {
        imgurl:'img/3.jpg',
        title:'Deutschland, Watzmann ',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/4.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/5.jpg',
        title:'Europe, Germany, Bavaria ',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/6.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/7.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/8.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/9.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/10.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/11.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/12.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/13.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/14.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/15.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/16.jpg',
        title:'Trail, Watzmann, Berchtesgaden',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/17.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/18.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/19.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/20.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/21.jpg',
        title:'Watzmann, Berchtesgaden',
        publi:'Pixabay',
        price:'₹20'
    },
    {
        imgurl:'img/22.jpg',
        title:'1',
        publi:'Pixabay',
        price:'₹20'
    }
];
export default PicDatas;